remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Virginie PAGEAUD (CASAVECCHIA)]
description: [Recueil de mes sketch·notes de conférences et autres événements]
show_downloads: false