remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Le blog de Vivi sensei]
description: [Recueil de sketchnotes par Virginie Pageaud (Casavecchia)]
show_downloads: false